# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 11:07
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=80, verbose_name='ip地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0, verbose_name='三级分类')),
                ('second_id', models.IntegerField(default=0, verbose_name='二级分类')),
                ('first_id', models.IntegerField(default=0, verbose_name='一级分类')),
                ('goods_sn', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='商品唯一的货号')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='商品名')),
                ('url', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='商品连接')),
                ('brand', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='商品品牌')),
                ('click_num', models.IntegerField(blank=True, default=0, verbose_name='点击数')),
                ('sold_num', models.IntegerField(blank=True, default=0, verbose_name='商品的销售量')),
                ('fav_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('goods_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='库存数')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='本店价格')),
                ('goods_brief', models.TextField(blank=True, max_length=500, null=True, verbose_name='商品简短描述')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
            },
        ),
    ]
