# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wxNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
