# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconcernlove',
            name='concertuser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='被关注人', to=settings.AUTH_USER_MODEL, verbose_name='被关注人'),
        ),
        migrations.AddField(
            model_name='userconcernlove',
            name='userConcern',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
